# Help Commands
.PHONY: default
default: help

# Main Commands
.PHONY: test
test:
	cargo llvm-cov --html

.PHONY: help
help:
	@echo 'Usage: make [command]'
	@echo 'test     - Run the cargo llvm-cov with html output'
